
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Main Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: 'npm'
    - run: npm ci
    - run: npm run eslint src/assets/js
